### ISSUE TITLE
Saving Printer Configuration Causes Dropped HTTPS Connection

### ISSUE THREAD

**Issue by sjoubani** [michaelrsweet/hp-printer-app#9] opened 2021-08-23 21:04 UTC
**Describe the bug**
When saving a printer's configuration (POST to <NAME>/config), the server-side connection is dropped, though the process itself doesn't terminate.

**To Reproduce**
1. Built on macOS (10.15, libpng 1.6.37, libusb 1.0.24, libjpeg 9d, PAPPL 1.0.3, h-p-a 66aba65)
2. Launch with "server" command
3. Browse in Safari and add a printer
4. Edit the printer's configuration (location, contact, etc)
5. Save changes

**Expected behavior**
POST succeeds and redirects to configuration page

**Screenshots**
<img width="644" alt="Screen Shot 2021-08-23 at 5 00 10 PM" src="https://user-images.githubusercontent.com/89421610/130518925-bb032ca7-58d4-40f2-b27d-dcf55431ffa5.png">

**System Information:**
 - macOS Catalina 10.15.7 19H1323
 - Safari 14.1.2
 - 66aba65

**Additional context**
This seems to be the only POST with this behavior, at least in this build

**Comment by michaelrsweet** [comment] 2021-08-24 12:06
@sjoubani Can you provide a debug log from this? I suspect the issue is in how Apple has changed keychain security in macOS, and that the self-signed certificate is not accessible to the printer application, causing this failure.

**Comment by sjoubani** [comment] 2021-08-24 16:13
@michaelrsweet The SSL connection works fine, and I've deliberately set HOME to a special location for the creation of .cups/ ssl.keychain. I've also set log-file and log-level as you requested to capture this:
[hp-printer-app.log](https://github.com/michaelrsweet/hp-printer-app/files/7040589/hp-printer-app.log)

**Comment by michaelrsweet** [comment] 2022-05-05 14:36
This seems to be fixed now.

**Closed as completed by michaelrsweet** 2022-05-05 14:36 UTC
